//
//  PaymentsHomeViewController.swift
//  Payer
//
//  Created by Emin on 21.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PaymentsHomeViewController: UIViewController {

    // MARK: - Public properties -

    @IBOutlet weak var walletLogo: UIImageView!
    var presenter: PaymentsHomePresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        navigationController?.setNavigationBarHidden(true, animated: false)
        
    }

}

// MARK: - Extensions -

extension PaymentsHomeViewController: PaymentsHomeViewInterface {
}
