//
//  PaymentsHomePresenter.swift
//  Payer
//
//  Created by Emin on 21.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PaymentsHomePresenter {

    // MARK: - Private properties -

    private unowned let view: PaymentsHomeViewInterface
    private let interactor: PaymentsHomeInteractorInterface
    private let wireframe: PaymentsHomeWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: PaymentsHomeViewInterface,
        interactor: PaymentsHomeInteractorInterface,
        wireframe: PaymentsHomeWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension PaymentsHomePresenter: PaymentsHomePresenterInterface {
    func saveTransaction(transaction: TransactionItem) {
        interactor.saveTransaction(transaction: transaction)
    }
    
    func saveCard(card: BankCardItem) {
        interactor.saveCard(card: card)
    }
    
    func loadCardData() -> [BankCardItem] {
        interactor.loadCardData()
    }
    
    func loadTransactions() -> [TransactionItem] {
        interactor.loadTransactions()
    }
    
}
