//
//  PaymentsHomeWireframe.swift
//  Payer
//
//  Created by Emin on 21.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PaymentsHomeWireframe: BaseWireframe<PaymentsHomeViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "PaymentsHome", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: PaymentsHomeViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = PaymentsHomeInteractor()
        let presenter = PaymentsHomePresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension PaymentsHomeWireframe: PaymentsHomeWireframeInterface {
    func routeToTransactionDetails(item: TransactionItem) {
        
    }
    
    func routeToTransactionScene() {
        
    }
    
}
