//
//  PaymentsHomeInterfaces.swift
//  Payer
//
//  Created by Emin on 21.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol PaymentsHomeWireframeInterface: WireframeInterface {
}

protocol PaymentsHomeViewInterface: ViewInterface {
    func setCardDataToUI()
}

protocol PaymentsHomePresenterInterface: PresenterInterface {
    func loadCardData() -> [BankCardItem]
    func loadTransactions() -> [TransactionItem]
    func saveTransaction(transaction:TransactionItem)
    func saveCard(card:BankCardItem)
}

protocol PaymentsHomeInteractorInterface: InteractorInterface {
    func loadCardData() -> [BankCardItem]
    func loadTransactions() -> [TransactionItem]
    func saveTransaction(transaction:TransactionItem)
    func saveCard(card:BankCardItem)
}
