//
//  PaymentsHomeInteractor.swift
//  Payer
//
//  Created by Emin on 21.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PaymentsHomeInteractor {
}

// MARK: - Extensions -

extension PaymentsHomeInteractor: PaymentsHomeInteractorInterface {
}
