//
//  PaymentsHomeInterfaces.swift
//  Payer
//
//  Created by Emin on 21.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol PaymentsHomeWireframeInterface: WireframeInterface {
    func routeToTransactionDetails(item:TransactionItem)
    func routeToTransactionScene()
}

protocol PaymentsHomeViewInterface: ViewInterface {
    func stopIndicator()
    func updateCard(cardModel: CardUIViewModel)
    func updateTable(transactions:[TransactionItem])
}

protocol PaymentsHomePresenterInterface: PresenterInterface {
    func viewDidLoad()
    var numberOfRows: Int { get }
    func transactionAtIndex(index:Int) -> TransactionItem
    func didSelectRow(index:Int)
}

protocol PaymentsHomeInteractorInterface: InteractorInterface {
    func loadCardData(completion: @escaping ((Result<[BankCardItem], Error>) -> Void)) 
    func loadTransactions(completion: @escaping ((Result<[TransactionItem], Error>) -> Void))
}
