//
//  PaymentsHomeInterfaces.swift
//  Payer
//
//  Created by Emin on 21.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol PaymentsHomeWireframeInterface: WireframeInterface {
}

protocol PaymentsHomeViewInterface: ViewInterface {
}

protocol PaymentsHomePresenterInterface: PresenterInterface {
}

protocol PaymentsHomeInteractorInterface: InteractorInterface {
}
