//
//  PaymentsHomeInteractor.swift
//  Payer
//
//  Created by Emin on 21.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PaymentsHomeInteractor {
    private let coreDataStack: CoreDataStack = CoreDataStack()
    private var payerStore: PayerStoreProtocol
    
    init (payerStore: PayerStoreProtocol? = nil){
        // Allows injection
        if let payerStore = payerStore {
            self.payerStore = payerStore
        }else {
            self.payerStore =  PayerStore(managedObjectContext: coreDataStack.mainContext, coreDataStack: coreDataStack)
        }
       
    }
}

// MARK: - Extensions -

extension PaymentsHomeInteractor: PaymentsHomeInteractorInterface {
    
    func loadCardData(completion: @escaping ((Result<[BankCardItem], Error>) -> Void)) {
        payerStore.getCardInfo { result in
            completion(result)
        }
    }
    
    func loadTransactions(completion: @escaping ((Result<[TransactionItem], Error>) -> Void)) {
        payerStore.getTransactions { result in
            completion(result)
        }
    }
    
}
