//
//  PaymentsHomeViewController.swift
//  Payer
//
//  Created by Emin on 21.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import NVActivityIndicatorView

final class PaymentsHomeViewController: UIViewController {

    // MARK: - Public properties -

    @IBOutlet weak var headerView: UIView!
    
    @IBOutlet weak var balanceLabel: UILabel!
    @IBOutlet weak var balanceAmount: UILabel!
    @IBOutlet weak var payButtonLabel: UILabel!
    
    @IBOutlet weak var creditCardView: CreditCardView!
    
    @IBOutlet weak var nvActivityIndicator: NVActivityIndicatorView!
    @IBOutlet weak var transactionsTable: TransactionHistoryTable!
    var presenter: PaymentsHomePresenterInterface!

    @IBAction func payButtonAction(_ sender: Any) {
        presenter.makePayment()
    }
    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        navigationController?.setNavigationBarHidden(true, animated: false)
       
        nvActivityIndicator.startAnimating()
       
        transactionsTable.presenter = presenter
        
        payButtonLabel.text = NSLocalizedString("paybuttonLabel", comment: "")
    }
    
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.setNavigationBarHidden(true, animated: false)
        presenter.viewWillAppear()
    }


}

// MARK: - Extensions -

extension PaymentsHomeViewController: PaymentsHomeViewInterface {
    func stopIndicator() {
        nvActivityIndicator.stopAnimating()
    }
    
    func updateCard(cardModel: CardUIViewModel) {
        creditCardView.cardNumber.text = cardModel.cardNumber
        creditCardView.userName.text = cardModel.userName
        creditCardView.expDate.text = cardModel.expDate
        creditCardView.cvvDate.text = cardModel.cvv
        balanceAmount.text = cardModel.balance
    }
    
    func updateTable(transactions: [TransactionItem]) {
        transactionsTable.tableViewData = transactions
    }
    

}
