//
//  MakePaymentInterfaces.swift
//  Payer
//
//  Created by Emin on 22.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MakePaymentWireframeInterface: WireframeInterface {
    func moneyTransfer()
}

protocol MakePaymentViewInterface: ViewInterface {
}

protocol MakePaymentPresenterInterface: PresenterInterface {
    func viewDidLoad()
    func numberOfRowForSection(section: PaymentSections) -> Int 
    var numberOfSections: Int { get }
    func paymentTypeAtIndex(index:IndexPath,tableView:UITableView) -> PaymentTypeTableViewCell
    func didSelectRow(index:Int)
    var cellIdentifier: String { get }
}

protocol MakePaymentInteractorInterface: InteractorInterface {
    func getAvailableTransactionTypes() -> [AvailableTransactionTypes]
    func getSubscriptions(completion: @escaping ((Result<[SubscriptionItem], Error>) -> Void))
}
