//
//  MakePaymentWireframe.swift
//  Payer
//
//  Created by Emin on 22.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MakePaymentWireframe: BaseWireframe<MakePaymentViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "MakePayment", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: MakePaymentViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = MakePaymentInteractor()
        let presenter = MakePaymentPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension MakePaymentWireframe: MakePaymentWireframeInterface {
}
