//
//  MakePaymentPresenter.swift
//  Payer
//
//  Created by Emin on 22.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MakePaymentPresenter {

    // MARK: - Private properties -

    private unowned let view: MakePaymentViewInterface
    private let interactor: MakePaymentInteractorInterface
    private let wireframe: MakePaymentWireframeInterface

    // MARK: - Lifecycle -

    private var availableTransactionTypes: [AvailableTransactionTypes] = []
    init(
        view: MakePaymentViewInterface,
        interactor: MakePaymentInteractorInterface,
        wireframe: MakePaymentWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension MakePaymentPresenter: MakePaymentPresenterInterface {

    var cellIdentifier: String {
        return String(describing: PaymentTypeTableViewCell.self)
    }
    
    var numberOfSections: Int {
        return 2
    }
    
    func numberOfRowForSection(section: PaymentSections) -> Int {
        switch section {
        case .transfer:
            return 1
        case .subscriptions:
            return availableTransactionTypes.count
        }
    }
    
    
    func viewDidLoad() {
        availableTransactionTypes = interactor.getAvailableTransactionTypes()
    }

    func paymentTypeAtIndex(index: IndexPath,tableView:UITableView) -> PaymentTypeTableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: cellIdentifier) as! PaymentTypeTableViewCell
      
        if index.section == PaymentSections.transfer.rawValue {
            cell.paymentImage.image = UIImage(named: "TransferIcon")
            cell.paymentLabel.text = NSLocalizedString("payment_Transfer", comment: "")
        }else {
            setCellDataForSubscriptions(data: AvailableTransactionTypes(rawValue: index.row) ?? .apple, cell: cell)
        }
       return cell
    }
    
    private func setCellDataForSubscriptions(data:AvailableTransactionTypes,cell:PaymentTypeTableViewCell){
        switch data {
        case .apple:
            cell.paymentImage.image = UIImage(named: "AppleIcon")
            cell.paymentLabel.text = NSLocalizedString("payment_Apple", comment: "")
        case .amazon:
            cell.paymentImage.image = UIImage(named: "AmazonIcon")
            cell.paymentLabel.text = NSLocalizedString("payment_Amazon", comment: "")
        case .netflix:
            cell.paymentImage.image = UIImage(named: "NetflixIcon")
            cell.paymentLabel.text = NSLocalizedString("payment_Netflix", comment: "")
        case .spotify:
            cell.paymentImage.image = UIImage(named: "SpotifyIcon")
            cell.paymentLabel.text = NSLocalizedString("payment_Spotify", comment: "")
        }
    }
    
    func didSelectRow(index: Int) {
        //TODO: imp
    }
    
}

enum PaymentSections: Int{
    case transfer
    case subscriptions
}
