//
//  FinishPaymentViewController.swift
//  Payer
//
//  Created by Emin on 22.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import NVActivityIndicatorView

final class FinishPaymentViewController: UIViewController {

    // MARK: - Public properties -

    @IBOutlet weak var ibanField: GenericTextField!
    @IBOutlet weak var nameField: GenericTextField!
    @IBOutlet weak var noteField: GenericTextField!
    @IBOutlet weak var amountField: GenericTextField!
    var presenter: FinishPaymentPresenterInterface!

    @IBOutlet weak var transferButtonOutlet: UIButton!
    // MARK: - Lifecycle -

    @IBOutlet weak var indicator: NVActivityIndicatorView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        setGenericTextFieldDatas()
        
        transferButtonOutlet.titleLabel?.text = NSLocalizedString("transferButtonLabel", comment: "")
        
    }
    
    @IBAction func transferButtonAction(_ sender: Any) {
        indicator.startAnimating()
        presenter.transferButtonAction(transferDatas: [ibanField.getData(),
                                                       nameField.getData(),
                                                       noteField.getData(),
                                                       amountField.getData()])
    }

    private func setGenericTextFieldDatas(){
        let data =  presenter.getGenericTexFieldDatas()
        
        ibanField.setData(data: data[0])
        nameField.setData(data: data[1])
        noteField.setData(data: data[2])
        amountField.setData(data: data[3])
    }
}

// MARK: - Extensions -

extension FinishPaymentViewController: FinishPaymentViewInterface {
    func stopIndicator() {
        indicator.stopAnimating()
    }
    
}
