//
//  FinishPaymentInteractor.swift
//  Payer
//
//  Created by Emin on 22.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class FinishPaymentInteractor {
    private let coreDataStack: CoreDataStack = CoreDataStack()
    private var payerStore: PayerStoreProtocol
    
    init (payerStore: PayerStoreProtocol? = nil){
        // Allows injection
        if let payerStore = payerStore {
            self.payerStore = payerStore
        }else {
            self.payerStore =  PayerStore(managedObjectContext: coreDataStack.mainContext, coreDataStack: coreDataStack)
        }
       
    }
}

// MARK: - Extensions -

extension FinishPaymentInteractor: FinishPaymentInteractorInterface {
    func executeTransfer(iban:String,
                         to:String,
                         note:String,
                         amount:NSDecimalNumber,
                         completion: @escaping ((Result<TransactionData, Error>) -> Void)) {

        let ownerName = UserDefaults.standard.string(forKey: "CardOwner")
        
        let transaction = TransactionItem(date: Date.now,
                                          currency: "EUR",
                                          details: note,
                                          title: "payment_Transfer",
                                          from: ownerName,
                                          to: to,
                                          amount: amount,
                                          charge: 2)
        
        payerStore.saveTransaction(transaction: transaction) { result in
            completion(result)
        }
        
        
    }
    
}
