//
//  FinishPaymentInterfaces.swift
//  Payer
//
//  Created by Emin on 22.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol FinishPaymentWireframeInterface: WireframeInterface {
    func dismiss()
}

protocol FinishPaymentViewInterface: ViewInterface {
    func stopIndicator()
}

protocol FinishPaymentPresenterInterface: PresenterInterface {
    func getGenericTexFieldDatas() -> [GenericTextFieldData]
    func transferButtonAction(transferDatas:[GenericTextFieldData])
}

protocol FinishPaymentInteractorInterface: InteractorInterface {
    func executeTransfer(iban:String,
                         to:String,
                         note:String,
                         amount:NSDecimalNumber,
                         completion: @escaping ((Result<TransactionData, Error>) -> Void))
}
