//
//  PaymentDetailsWireframe.swift
//  Payer
//
//  Created by Emin on 22.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PaymentDetailsWireframe: BaseWireframe<PaymentDetailsViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "PaymentDetails", bundle: nil)

    // MARK: - Module setup -

    init(transaction:TransactionItem) {
        let moduleViewController = storyboard.instantiateViewController(ofType: PaymentDetailsViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = PaymentDetailsInteractor()
        let presenter = PaymentDetailsPresenter(view: moduleViewController, interactor: interactor, wireframe: self, transaction: transaction)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension PaymentDetailsWireframe: PaymentDetailsWireframeInterface {
}
