//
//  PaymentDetailsInteractor.swift
//  Payer
//
//  Created by Emin on 22.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PaymentDetailsInteractor {
}

// MARK: - Extensions -

extension PaymentDetailsInteractor: PaymentDetailsInteractorInterface {
}
